let vocab =[
["Hola "," Hello"],
["Adiós"," Goodbye"],
["Hasta luego ","See you later"],
["Buenos días ","Good morning"],
["Buenas tardes"," Good afternoon"],
["Buenas noches"," Good night"],
["Sí"," Yes"],
["No"," No"],
["Nos vamos "," See you later"],
["Hasta mañana"," See you tomorrow"],
["¿Cuál es tu nombre "," What is your name?"],
["mi nombre es Rosa"," I'm Rosa"],
["Yo soy Rosa "," I'm Rosa"],
["Encantado de conocerle"," Nice to meet you  (formal)"],
["Encantado de conocerte "," Nice to meet you  (informal)"],
["De nada "," You are welcome"],
["Gracias "," Thank you"],
["No hay de qué "," Don't mention it"],
["Por favor "," Please"],
["¿Perdón ? "," excuse me?"],
["Lo siento "," I'm sorry"],
["Bienvenidos "," welcome"],
["Cómo estás"," How are you? (unformal)"],
["Qué tal"," How are you? (formal)"],
["¿Qué hora es?"," What time is it?"],
["¿Cuánto es, or cuánto questa "," How much?"],
["¿Qué es eso? "," what is this ?"],
["¿En dónde está el baño?", "Where is the bathroom ?"],
["No lo comprendo, or No lo entiendo"," I don't understand"]
];	
